name: Rev Doc Denise Hall
favicon: null
layout_spectrum: 0.0341737091075629
typography_spectrum: 0.16127856145612895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7100672905799001
  lightness: 0.2907652906142175
  saturation: 0.5300949271768332
  rhythmicContrast: 0.6086800477933139
purpose: []
